name: Continuous Integration
on: push

jobs:
  job1:
    runs-on: ubuntu-18.04
    outputs:
      random: ${{ steps.generate-random.outputs.random }}
    steps:
      - id: generate-random
        run: echo "::set-outputname=random::$(openssl rand -base64 12)"
  job2:
    runs-on: ubuntu-18.04
    needs: job1
    steps:
      - run: echo "${{ needs.job1.outputs.random }}"