name: Artifact Test
on: push

jobs:
  upload:
    runs-on: ubuntu-18.04
    steps:
      - run: |
          mkdir data
          echo "Hello" > data/hello.txt
      - uses: actions/upload-artifact@v2
        with:
          name: data
          path: data
  download:
    runs-on: ubuntu-18.04
    needs: upload
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: data
      - run: cat hello.txt